version: "3"
services:

  dictionary:
    image: jgoyette/dictionary:latest
    ports:
      - 3001:3001
    networks:
      - dictionary_app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  node:
    image: jgoyette/node:latest
    ports:
      - 3000:3000
    networks:
      - dictionary_app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  dictionary_app: